<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class PermissionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        /**
         * Create all permissions.
         *
         * EVERYTHING HERE IS USED IN A SINGULAR SENSE
         */

        // Permissions for school


        $permissions = [
            ["guard_name"  => 'web', 'name' => 'header-administrate',],
            ["guard_name"  => 'web', 'name' => 'header-schools',],
            ["guard_name"  => 'web', 'name' => 'header-academics',],
            ["guard_name"  => 'web', 'name' => 'menu-class',],
            ["guard_name"  => 'web', 'name' => 'menu-section',],
            ["guard_name"  => 'web', 'name' => 'menu-student',],
            ["guard_name"  => 'web', 'name' => 'menu-teacher',],
            ["guard_name"  => 'web', 'name' => 'menu-parent',],
            ["guard_name"  => 'web', 'name' => 'menu-academic-year',],
            ["guard_name"  => 'web', 'name' => 'menu-semester',],
            ["guard_name"  => 'web', 'name' => 'menu-subject',],
            ["guard_name"  => 'web', 'name' => 'menu-syllabus',],
            ["guard_name"  => 'web', 'name' => 'menu-timetable',],
            ["guard_name"  => 'web', 'name' => 'menu-exam',],
            ["guard_name"  => 'web', 'name' => 'menu-grade-system',],
            ["guard_name"  => 'web', 'name' => 'menu-notice',],
            ["guard_name"  => 'web', 'name' => 'menu-account-application',],
            ["guard_name"  => 'web', 'name' => 'menu-attendance',],
            ["guard_name"  => 'web', 'name' => 'menu-documents',],
            ["guard_name"  => 'web', 'name' => 'menu-fees',],
            ["guard_name"  => 'web', 'name' => 'menu-transport',],
            ["guard_name"  => 'web', 'name' => 'menu-finance',],
            ["guard_name"  => 'web', 'name' => 'menu-staff',],
            ["guard_name"  => 'web', 'name' => 'menu-class-work',],
            ["guard_name"  => 'web', 'name' => 'menu-home-work',],
            ["guard_name"  => 'web', 'name' => 'menu-salary',],
            ["guard_name"  => 'web', 'name' => 'menu-library',],
            ["guard_name"  => 'web', 'name' => 'menu-software-plan',],
            ["guard_name"  => 'web', 'name' => 'menu-payment-plan',],
            ["guard_name"  => 'web', 'name' => 'menu-leave',],




            ["guard_name"  => 'web', 'name' => 'create staff-admin',],
            ["guard_name"  => 'web', 'name' => 'read staff-admin',],
            ["guard_name"  => 'web', 'name' => 'update staff-admin',],
            ["guard_name"  => 'web', 'name' => 'delete staff-admin',],
            ["guard_name"  => 'web', 'name' => 'create staff-manager',],
            ["guard_name"  => 'web', 'name' => 'read staff-manager',],
            ["guard_name"  => 'web', 'name' => 'update staff-manager',],
            ["guard_name"  => 'web', 'name' => 'delete staff-manager',],
            ["guard_name"  => 'web', 'name' => 'create staff-principle',],
            ["guard_name"  => 'web', 'name' => 'read staff-principle',],
            ["guard_name"  => 'web', 'name' => 'update staff-principle',],
            ["guard_name"  => 'web', 'name' => 'delete staff-principle',],
            ["guard_name"  => 'web', 'name' => 'create staff-incharge',],
            ["guard_name"  => 'web', 'name' => 'read staff-incharge',],
            ["guard_name"  => 'web', 'name' => 'update staff-incharge',],
            ["guard_name"  => 'web', 'name' => 'delete staff-incharge',],
            ["guard_name"  => 'web', 'name' => 'create staff-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'read staff-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'update staff-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'delete staff-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'create staff-teacher',],
            ["guard_name"  => 'web', 'name' => 'read staff-teacher',],
            ["guard_name"  => 'web', 'name' => 'update staff-teacher',],
            ["guard_name"  => 'web', 'name' => 'delete staff-teacher',],
            ["guard_name"  => 'web', 'name' => 'create staff-driver',],
            ["guard_name"  => 'web', 'name' => 'read staff-driver',],
            ["guard_name"  => 'web', 'name' => 'update staff-driver',],
            ["guard_name"  => 'web', 'name' => 'delete staff-driver',],

            ["guard_name"  => 'web', 'name' => 'create staff-own-manager',],
            ["guard_name"  => 'web', 'name' => 'read staff-own-manager',],
            ["guard_name"  => 'web', 'name' => 'update staff-own-manager',],
            ["guard_name"  => 'web', 'name' => 'delete staff-own-manager',],
            ["guard_name"  => 'web', 'name' => 'create staff-own-admin',],
            ["guard_name"  => 'web', 'name' => 'read staff-own-admin',],
            ["guard_name"  => 'web', 'name' => 'update staff-own-admin',],
            ["guard_name"  => 'web', 'name' => 'delete staff-own-admin',],
            ["guard_name"  => 'web', 'name' => 'create staff-own-principle',],
            ["guard_name"  => 'web', 'name' => 'read staff-own-principle',],
            ["guard_name"  => 'web', 'name' => 'update staff-own-principle',],
            ["guard_name"  => 'web', 'name' => 'delete staff-own-principle',],
            ["guard_name"  => 'web', 'name' => 'create staff-own-incharge',],
            ["guard_name"  => 'web', 'name' => 'read staff-own-incharge',],
            ["guard_name"  => 'web', 'name' => 'update staff-own-incharge',],
            ["guard_name"  => 'web', 'name' => 'delete staff-own-incharge',],
            ["guard_name"  => 'web', 'name' => 'create staff-own-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'read staff-own-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'update staff-own-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'delete staff-own-class-teacher',],
            ["guard_name"  => 'web', 'name' => 'create staff-own-teacher',],
            ["guard_name"  => 'web', 'name' => 'read staff-own-teacher',],
            ["guard_name"  => 'web', 'name' => 'update staff-own-teacher',],
            ["guard_name"  => 'web', 'name' => 'delete staff-own-teacher',],
            ["guard_name"  => 'web', 'name' => 'create staff-own-student',],
            ["guard_name"  => 'web', 'name' => 'read staff-own-student',],
            ["guard_name"  => 'web', 'name' => 'update staff-own-student',],
            ["guard_name"  => 'web', 'name' => 'delete staff-own-student',],

            ["guard_name"  => 'web', 'name' => 'create leave',],
            ["guard_name"  => 'web', 'name' => 'read leave',],
            ["guard_name"  => 'web', 'name' => 'update leave',],
            ["guard_name"  => 'web', 'name' => 'delete leave',],


            ["guard_name"  => 'web', 'name' => 'create school',],
            ["guard_name"  => 'web', 'name' => 'read school',],
            ["guard_name"  => 'web', 'name' => 'update school',],
            ["guard_name"  => 'web', 'name' => 'delete school',],
            ["guard_name"  => 'web', 'name' => 'create library',],
            ["guard_name"  => 'web', 'name' => 'read library',],
            ["guard_name"  => 'web', 'name' => 'update library',],
            ["guard_name"  => 'web', 'name' => 'delete library',],

            ["guard_name"  => 'web', 'name' => 'manage school settings',],
            ["guard_name"  => 'web', 'name' => 'create class group',],
            ["guard_name"  => 'web', 'name' => 'read class group',],
            ["guard_name"  => 'web', 'name' => 'update class group',],
            ["guard_name"  => 'web', 'name' => 'delete class group',],
            ["guard_name"  => 'web', 'name' => 'create class',],
            ["guard_name"  => 'web', 'name' => 'read class',],
            ["guard_name"  => 'web', 'name' => 'update class',],
            ["guard_name"  => 'web', 'name' => 'update class',],
            ["guard_name"  => 'web', 'name' => 'delete class',],
            ["guard_name"  => 'web', 'name' => 'create section',],
            ["guard_name"  => 'web', 'name' => 'read section',],
            ["guard_name"  => 'web', 'name' => 'update section',],
            ["guard_name"  => 'web', 'name' => 'delete section',],
            ["guard_name"  => 'web', 'name' => 'create student',],
            ["guard_name"  => 'web', 'name' => 'read student',],
            ["guard_name"  => 'web', 'name' => 'update student',],
            ["guard_name"  => 'web', 'name' => 'delete student',],
            ["guard_name"  => 'web', 'name' => 'withdraw student',],
            ["guard_name"  => 'web', 'name' => 'create academic year',],
            ["guard_name"  => 'web', 'name' => 'read academic year',],
            ["guard_name"  => 'web', 'name' => 'update academic year',],
            ["guard_name"  => 'web', 'name' => 'delete academic year',],
            ["guard_name"  => 'web', 'name' => 'set academic year',],
            ["guard_name"  => 'web', 'name' => 'create teacher',],
            ["guard_name"  => 'web', 'name' => 'read teacher',],
            ["guard_name"  => 'web', 'name' => 'update teacher',],
            ["guard_name"  => 'web', 'name' => 'delete teacher',],
            ["guard_name"  => 'web', 'name' => 'read role asignment',],
            ["guard_name"  => 'web', 'name' => 'create parent',],
            ["guard_name"  => 'web', 'name' => 'read parent',],
            ["guard_name"  => 'web', 'name' => 'update parent',],
            ["guard_name"  => 'web', 'name' => 'delete parent',],
            ["guard_name"  => 'web', 'name' => 'create subject',],
            ["guard_name"  => 'web', 'name' => 'read subject',],
            ["guard_name"  => 'web', 'name' => 'update subject',],
            ["guard_name"  => 'web', 'name' => 'delete subject',],
            ["guard_name"  => 'web', 'name' => 'promote student',],
            ["guard_name"  => 'web', 'name' => 'read promotion',],
            ["guard_name"  => 'web', 'name' => 'reset promotion',],
            ["guard_name"  => 'web', 'name' => 'graduate student',],
            ["guard_name"  => 'web', 'name' => 'read graduations',],
            ["guard_name"  => 'web', 'name' => 'reset graduation',],
            ["guard_name"  => 'web', 'name' => 'create semester',],
            ["guard_name"  => 'web', 'name' => 'read semester',],
            ["guard_name"  => 'web', 'name' => 'update semester',],
            ["guard_name"  => 'web', 'name' => 'delete semester',],
            ["guard_name"  => 'web', 'name' => 'set semester',],
            ["guard_name"  => 'web', 'name' => 'create syllabus',],
            ["guard_name"  => 'web', 'name' => 'read syllabus',],
            ["guard_name"  => 'web', 'name' => 'update syllabus',],
            ["guard_name"  => 'web', 'name' => 'delete syllabus',],
            ["guard_name"  => 'web', 'name' => 'create timetable',],
            ["guard_name"  => 'web', 'name' => 'read timetable',],
            ["guard_name"  => 'web', 'name' => 'update timetable',],
            ["guard_name"  => 'web', 'name' => 'delete timetable',],
            ["guard_name"  => 'web', 'name' => 'create custom timetable item',],
            ["guard_name"  => 'web', 'name' => 'read custom timetable item',],
            ["guard_name"  => 'web', 'name' => 'update custom timetable item',],
            ["guard_name"  => 'web', 'name' => 'delete custom timetable item',],
            ["guard_name"  => 'web', 'name' => 'create exam',],
            ["guard_name"  => 'web', 'name' => 'read exam',],
            ["guard_name"  => 'web', 'name' => 'update exam',],
            ["guard_name"  => 'web', 'name' => 'delete exam',],
            ["guard_name"  => 'web', 'name' => 'exam type',],
            ["guard_name"  => 'web', 'name' => 'exam schea',],
            ["guard_name"  => 'web', 'name' => 'exam admit card',],
            ["guard_name"  => 'web', 'name' => 'exam desk slip',],
            ["guard_name"  => 'web', 'name' => 'exam result sheet',],
            ["guard_name"  => 'web', 'name' => 'exam marksheet',],
            ["guard_name"  => 'web', 'name' => 'exam tc form',],
            ["guard_name"  => 'web', 'name' => 'exam tc',],
            ["guard_name"  => 'web', 'name' => 'exam character certificate',],
            ["guard_name"  => 'web', 'name' => 'create grade system',],
            ["guard_name"  => 'web', 'name' => 'read grade system',],
            ["guard_name"  => 'web', 'name' => 'update grade system',],
            ["guard_name"  => 'web', 'name' => 'delete grade system',],
            ["guard_name"  => 'web', 'name' => 'create exam slot',],
            ["guard_name"  => 'web', 'name' => 'read exam slot',],
            ["guard_name"  => 'web', 'name' => 'update exam slot',],
            ["guard_name"  => 'web', 'name' => 'delete exam slot',],
            ["guard_name"  => 'web', 'name' => 'create exam record',],
            ["guard_name"  => 'web', 'name' => 'read exam record',],
            ["guard_name"  => 'web', 'name' => 'update exam record',],
            ["guard_name"  => 'web', 'name' => 'delete exam record',],
            ["guard_name"  => 'web', 'name' => 'check result',],
            ["guard_name"  => 'web', 'name' => 'create notice',],
            ["guard_name"  => 'web', 'name' => 'read notice',],
            ["guard_name"  => 'web', 'name' => 'update notice',],
            ["guard_name"  => 'web', 'name' => 'delete notice',],
            ["guard_name"  => 'web', 'name' => 'read applicant',],
            ["guard_name"  => 'web', 'name' => 'update applicant',],
            ["guard_name"  => 'web', 'name' => 'delete applicant',],
            ["guard_name"  => 'web', 'name' => 'change account application status',],


            ["guard_name"  => 'web', 'name' => 'read admin',],
            ["guard_name"  => 'web', 'name' => 'create admin',],
            ["guard_name"  => 'web', 'name' => 'edit admin',],
            ["guard_name"  => 'web', 'name' => 'delete admin',],
            ["guard_name"  => 'web', 'name' => 'permission admin',],
            ["guard_name"  => 'web', 'name' => 'read attendance',],
            ["guard_name"  => 'web', 'name' => 'create attendance',],
            ["guard_name"  => 'web', 'name' => 'edit attendance',],
            ["guard_name"  => 'web', 'name' => 'delete attendance',],
            ["guard_name"  => 'web', 'name' => 'read attendance-schedules',],
            ["guard_name"  => 'web', 'name' => 'create attendance-schedules',],
            ["guard_name"  => 'web', 'name' => 'edit attendance-schedules',],
            ["guard_name"  => 'web', 'name' => 'delete attendance-schedules',],
           
            ["guard_name"  => 'web', 'name' => 'read attendance register',],
            ["guard_name"  => 'web', 'name' => 'create attendance register',],
            ["guard_name"  => 'web', 'name' => 'edit attendance register',],
            ["guard_name"  => 'web', 'name' => 'delete attendance register',],
            ["guard_name"  => 'web', 'name' => 'read staff attendance',],
            ["guard_name"  => 'web', 'name' => 'create staff attendance',],
            ["guard_name"  => 'web', 'name' => 'edit staff attendance',],
            ["guard_name"  => 'web', 'name' => 'delete staff attendance',],
            ["guard_name"  => 'web', 'name' => 'read student attendance',],
            ["guard_name"  => 'web', 'name' => 'create student attendance',],
            ["guard_name"  => 'web', 'name' => 'edit student attendance',],
            ["guard_name"  => 'web', 'name' => 'delete student attendance',],
            ["guard_name"  => 'web', 'name' => 'read documents',],
            ["guard_name"  => 'web', 'name' => 'create documents',],
            ["guard_name"  => 'web', 'name' => 'edit documents',],
            ["guard_name"  => 'web', 'name' => 'delete documents',],

            ["guard_name"  => 'web', 'name' => 'read document-collage-logo',],
            ["guard_name"  => 'web', 'name' => 'create document-collage-logo',],
            ["guard_name"  => 'web', 'name' => 'edit document-collage-logo',],
            ["guard_name"  => 'web', 'name' => 'delete document-collage-logo',],
            ["guard_name"  => 'web', 'name' => 'read document-sign',],
            ["guard_name"  => 'web', 'name' => 'create document-sign',],
            ["guard_name"  => 'web', 'name' => 'edit document-sign',],
            ["guard_name"  => 'web', 'name' => 'delete document-sign',],
            ["guard_name"  => 'web', 'name' => 'read document-id-card',],
            ["guard_name"  => 'web', 'name' => 'create document-id-card',],
            ["guard_name"  => 'web', 'name' => 'edit document-id-card',],
            ["guard_name"  => 'web', 'name' => 'delete document-id-card',],
            ["guard_name"  => 'web', 'name' => 'read document-fees-card',],
            ["guard_name"  => 'web', 'name' => 'create document-fees-card',],
            ["guard_name"  => 'web', 'name' => 'edit document-fees-card',],
            ["guard_name"  => 'web', 'name' => 'delete document-fees-card',],
            ["guard_name"  => 'web', 'name' => 'read document-scheam',],
            ["guard_name"  => 'web', 'name' => 'create document-scheam',],
            ["guard_name"  => 'web', 'name' => 'edit document-scheam',],
            ["guard_name"  => 'web', 'name' => 'delete document-scheam',],
            ["guard_name"  => 'web', 'name' => 'read document-admit-card',],
            ["guard_name"  => 'web', 'name' => 'create document-admit-card',],
            ["guard_name"  => 'web', 'name' => 'edit document-admit-card',],
            ["guard_name"  => 'web', 'name' => 'delete document-admit-card',],
            ["guard_name"  => 'web', 'name' => 'read document-number-sheet',],
            ["guard_name"  => 'web', 'name' => 'create document-number-sheet',],
            ["guard_name"  => 'web', 'name' => 'edit document-number-sheet',],
            ["guard_name"  => 'web', 'name' => 'delete document-number-sheet',],
            ["guard_name"  => 'web', 'name' => 'read document-mark-sheet',],
            ["guard_name"  => 'web', 'name' => 'create document-mark-sheet',],
            ["guard_name"  => 'web', 'name' => 'edit document-mark-sheet',],
            ["guard_name"  => 'web', 'name' => 'delete document-mark-sheet',],

            ["guard_name"  => 'web', 'name' => 'read exam-exam-type',],
            ["guard_name"  => 'web', 'name' => 'create exam-exam-type',],
            ["guard_name"  => 'web', 'name' => 'edit exam-exam-type',],
            ["guard_name"  => 'web', 'name' => 'delete exam-exam-type',],


            ["guard_name"  => 'web', 'name' => 'read collage-documents',],
            ["guard_name"  => 'web', 'name' => 'create collage-documents',],
            ["guard_name"  => 'web', 'name' => 'edit collage-documents',],
            ["guard_name"  => 'web', 'name' => 'delete collage-documents',],
            ["guard_name"  => 'web', 'name' => 'read print-documents',],
            ["guard_name"  => 'web', 'name' => 'create print-documents',],
            ["guard_name"  => 'web', 'name' => 'edit print-documents',],
            ["guard_name"  => 'web', 'name' => 'delete print-documents',],
            ["guard_name"  => 'web', 'name' => 'read fees',],
            ["guard_name"  => 'web', 'name' => 'create fees',],
            ["guard_name"  => 'web', 'name' => 'edit fees',],
            ["guard_name"  => 'web', 'name' => 'delete fees',],
            ["guard_name"  => 'web', 'name' => 'read class-work',],
            ["guard_name"  => 'web', 'name' => 'create class-work',],
            ["guard_name"  => 'web', 'name' => 'edit class-work',],
            ["guard_name"  => 'web', 'name' => 'delete class-work',],
            ["guard_name"  => 'web', 'name' => 'read home-work',],
            ["guard_name"  => 'web', 'name' => 'create home-work',],
            ["guard_name"  => 'web', 'name' => 'edit home-work',],
            ["guard_name"  => 'web', 'name' => 'delete home-work',],
            ["guard_name"  => 'web', 'name' => 'read salary',],
            ["guard_name"  => 'web', 'name' => 'create salary',],
            ["guard_name"  => 'web', 'name' => 'edit salary',],
            ["guard_name"  => 'web', 'name' => 'delete salary',],



            ["guard_name"  => 'web', 'name' => 'read self-attendance',],
            ["guard_name"  => 'web', 'name' => 'edit self-attendance',],
            ["guard_name"  => 'web', 'name' => 'create self-attendance',],
            ["guard_name"  => 'web', 'name' => 'delete self-attendance',],
            ["guard_name"  => 'web', 'name' => 'read staff-attendance',],
            ["guard_name"  => 'web', 'name' => 'edit staff-attendance',],
            ["guard_name"  => 'web', 'name' => 'create staff-attendance',],
            ["guard_name"  => 'web', 'name' => 'delete staff-attendance',],
            ["guard_name"  => 'web', 'name' => 'read staff-attendance-register',],
            ["guard_name"  => 'web', 'name' => 'edit staff-attendance-register',],
            ["guard_name"  => 'web', 'name' => 'create staff-attendance-register',],
            ["guard_name"  => 'web', 'name' => 'delete staff-attendance-register',],
            ["guard_name"  => 'web', 'name' => 'read student-attendance',],
            ["guard_name"  => 'web', 'name' => 'edit student-attendance',],
            ["guard_name"  => 'web', 'name' => 'create student-attendance',],
            ["guard_name"  => 'web', 'name' => 'delete student-attendance',],
            ["guard_name"  => 'web', 'name' => 'read student-attendance-register',],
            ["guard_name"  => 'web', 'name' => 'edit student-attendance-register',],
            ["guard_name"  => 'web', 'name' => 'create student-attendance-register',],
            ["guard_name"  => 'web', 'name' => 'delete student-attendance-register',],


            ["guard_name"  => 'web', 'name' => 'read fees',],
            ["guard_name"  => 'web', 'name' => 'edit fees',],
            ["guard_name"  => 'web', 'name' => 'create fees',],
            ["guard_name"  => 'web', 'name' => 'delete fees',],
            ["guard_name"  => 'web', 'name' => 'read fees-status',],
            ["guard_name"  => 'web', 'name' => 'edit fees-status',],
            ["guard_name"  => 'web', 'name' => 'create fees-status',],
            ["guard_name"  => 'web', 'name' => 'delete fees-status',],
            
            ["guard_name"  => 'web', 'name' => 'read fees-slips',],
            ["guard_name"  => 'web', 'name' => 'edit fees-slips',],
            ["guard_name"  => 'web', 'name' => 'create fees-slips',],
            ["guard_name"  => 'web', 'name' => 'delete fees-slips',],
            ["guard_name"  => 'web', 'name' => 'read fees-card',],
            ["guard_name"  => 'web', 'name' => 'edit fees-card',],
            ["guard_name"  => 'web', 'name' => 'create fees-card',],
            ["guard_name"  => 'web', 'name' => 'delete fees-card',],

            ["guard_name"  => 'web', 'name' => 'read fees-consession',],
            ["guard_name"  => 'web', 'name' => 'edit fees-consession',],
            ["guard_name"  => 'web', 'name' => 'create fees-consession',],
            ["guard_name"  => 'web', 'name' => 'delete fees-consession',],

            ["guard_name"  => 'web', 'name' => 'read fees-collection',],
            ["guard_name"  => 'web', 'name' => 'edit fees-collection',],
            ["guard_name"  => 'web', 'name' => 'create fees-collection',],
            ["guard_name"  => 'web', 'name' => 'delete fees-collection',],



            ["guard_name"  => 'web', 'name' => 'read transport',],
            ["guard_name"  => 'web', 'name' => 'edit transport',],
            ["guard_name"  => 'web', 'name' => 'create transport',],
            ["guard_name"  => 'web', 'name' => 'delete transport',],

            ["guard_name"  => 'web', 'name' => 'read transport-fees',],
            ["guard_name"  => 'web', 'name' => 'edit transport-fees',],
            ["guard_name"  => 'web', 'name' => 'create transport-fees',],
            ["guard_name"  => 'web', 'name' => 'delete transport-fees',],
            ["guard_name"  => 'web', 'name' => 'read transport-assign-driver',],
            ["guard_name"  => 'web', 'name' => 'edit transport-assign-driver',],
            ["guard_name"  => 'web', 'name' => 'create transport-assign-driver',],
            ["guard_name"  => 'web', 'name' => 'delete transport-assign-driver',],
            ["guard_name"  => 'web', 'name' => 'read transport-student',],
            ["guard_name"  => 'web', 'name' => 'edit transport-student',],
            ["guard_name"  => 'web', 'name' => 'create transport-student',],
            ["guard_name"  => 'web', 'name' => 'delete transport-student',],
            ["guard_name"  => 'web', 'name' => 'read transport-vehicle-number',],
            ["guard_name"  => 'web', 'name' => 'edit transport-vehicle-number',],
            ["guard_name"  => 'web', 'name' => 'create transport-vehicle-number',],
            ["guard_name"  => 'web', 'name' => 'delete transport-vehicle-number',],
            ["guard_name"  => 'web', 'name' => 'read transport-root-driver',],
            ["guard_name"  => 'web', 'name' => 'edit transport-root-driver',],
            ["guard_name"  => 'web', 'name' => 'create transport-root-driver',],
            ["guard_name"  => 'web', 'name' => 'delete transport-root-driver',],



            ["guard_name"  => 'web', 'name' => 'read finance-incoming',],
            ["guard_name"  => 'web', 'name' => 'edit finance-incoming',],
            ["guard_name"  => 'web', 'name' => 'create finance-incoming',],
            ["guard_name"  => 'web', 'name' => 'delete finance-incoming',],
            ["guard_name"  => 'web', 'name' => 'read finance-expences',],
            ["guard_name"  => 'web', 'name' => 'edit finance-expences',],
            ["guard_name"  => 'web', 'name' => 'create finance-expences',],
            ["guard_name"  => 'web', 'name' => 'delete finance-expences',],

            ["guard_name"  => 'web', 'name' => 'read class-work',],
            ["guard_name"  => 'web', 'name' => 'edit class-work',],
            ["guard_name"  => 'web', 'name' => 'create class-work',],
            ["guard_name"  => 'web', 'name' => 'delete class-work',],
            ["guard_name"  => 'web', 'name' => 'read home-work',],
            ["guard_name"  => 'web', 'name' => 'edit home-work',],
            ["guard_name"  => 'web', 'name' => 'create home-work',],
            ["guard_name"  => 'web', 'name' => 'delete home-work',],

            ["guard_name"  => 'web', 'name' => 'read salary',],
            ["guard_name"  => 'web', 'name' => 'edit salary',],
            ["guard_name"  => 'web', 'name' => 'create salary',],
            ["guard_name"  => 'web', 'name' => 'delete salary',],
            ["guard_name"  => 'web', 'name' => 'read salary-distribute',],
            ["guard_name"  => 'web', 'name' => 'edit salary-distribute',],
            ["guard_name"  => 'web', 'name' => 'create salary-distribute',],
            ["guard_name"  => 'web', 'name' => 'delete salary-distribute',],

            ["guard_name"  => 'web', 'name' => 'read document',],
            ["guard_name"  => 'web', 'name' => 'edit document',],
            ["guard_name"  => 'web', 'name' => 'create document',],
            ["guard_name"  => 'web', 'name' => 'delete document',],
            ["guard_name"  => 'web', 'name' => 'create all-profile',],
            ["guard_name"  => 'web', 'name' => 'read-self-profile',],
            ["guard_name"  => 'web', 'name' => 'edit-self-profile',],
            ["guard_name"  => 'web', 'name' => 'create-self-profile',],
            ["guard_name"  => 'web', 'name' => 'delete-self-profile',],



        ];


        foreach ($permissions as $permission) {
            Permission::updateOrCreate(
                ['name' => $permission['name']],
                $permission
            );
        }


        // assign permission to super-admin
        $super_admin = Role::where('name', 'super-admin')->first();
        $super_admin->givePermissionTo([
            'menu-staff',
            'menu-teacher',
            'menu-student',
            'menu-class',
            'menu-attendance',
            'menu-documents',
            'menu-fees',
            'menu-timetable',
            'menu-transport',
            'menu-finance',
            'menu-class-work',
            'menu-home-work',
            'menu-salary',
            'menu-library',
            'menu-software-plan',
            'menu-payment-plan',

            'create all-profile',
            'read self-attendance',
            'read teacher',
            'read student',
            'read class',
            'create section',
            'read staff-attendance',
            'read staff-attendance-register',
            'read student-attendance',
            'read student-attendance-register',
            'read fees',
            'create fees',
            'read fees-consession',
            'read timetable',
            'read transport',
            'create transport',
            'read transport-fees',
            'create transport-fees',
            'create transport-assign-driver',
            'read transport-student',
            'read finance-incoming',
            'read finance-expences',
            'read class-work',
            'create class-work',
            'read home-work',
            'create home-work',
            'read salary',
            'read salary-distribute',
            'read document-collage-logo',
            'read document-sign',
            'read document-id-card',
            'read document-fees-card',
            'read document-scheam',
            'read document-admit-card',
            'read document-number-sheet',
            'read document-mark-sheet',
            'read exam-exam-type',
            'create staff-admin',
            'read staff-admin',
            'update staff-admin',
            'delete staff-admin',
            'create staff-manager',
            'read staff-manager',
            'update staff-manager',
            'delete staff-manager',
            'create staff-principle',
            'read staff-principle',
            'update staff-principle',
            'delete staff-principle',
            'create staff-incharge',
            'read staff-incharge',
            'update staff-incharge',
            'delete staff-incharge',
            'create staff-class-teacher',
            'read staff-class-teacher',
            'update staff-class-teacher',
            'delete staff-class-teacher',
            'create staff-teacher',
            'read staff-teacher',
            'update staff-teacher',
            'delete staff-teacher',
            'create library',
            'read library',
            'update library',
            'delete library',






        ]);

         //assign permissions to admin
         $admin = Role::where('name', 'admin')->first();
         $admin->givePermissionTo([
             'header-administrate',
             'header-academics',
             'menu-section',
             'menu-class',
             'menu-student',
             'menu-teacher',
             'menu-academic-year',
             'menu-subject',
             'menu-syllabus',
             'menu-timetable',
             'menu-semester',
             'menu-exam',
             'menu-grade-system',
             'menu-notice',
             'menu-parent',
             'menu-account-application',
             'manage school settings',
             'create section',
             'read section',
             'update section',
             'delete section',
             'create class',
             'read class',
             'update class',
             'delete class',
             'create class group',
             'read class group',
             'update class group',
             'delete class group',
             'create student',
             'read student',
             'update student',
             'delete student',
             'create academic year',
             'read academic year',
             'update academic year',
             'delete academic year',
             'set academic year',
             'create teacher',
             'read teacher',
             'update teacher',
             'delete teacher',
             'create subject',
             'read subject',
             'update subject',
             'delete subject',
             'promote student',
             'read promotion',
             'reset promotion',
             'graduate student',
             'read graduations',
             'reset graduation',
             'create semester',
             'read semester',
             'update semester',
             'delete semester',
             'set semester',
             'create syllabus',
             'read syllabus',
             'update syllabus',
             'delete syllabus',
             'create timetable',
             'read timetable',
             'update timetable',
             'delete timetable',
             'create custom timetable item',
             'read custom timetable item',
             'update custom timetable item',
             'delete custom timetable item',
             'create exam',
             'read exam',
             'update exam',
             'delete exam',
             'create grade system',
             'read grade system',
             'update grade system',
             'delete grade system',
             'create exam slot',
             'read exam slot',
             'update exam slot',
             'delete exam slot',
             'create exam record',
             'read exam record',
             'update exam record',
             'delete exam record',
             'create notice',
             'read notice',
             'update notice',
             'delete notice',
             'check result',
             'create parent',
             'read parent',
             'update parent',
             'delete parent',
             'read applicant',
             'update applicant',
             'delete applicant',
             'change account application status',
         ]);

        // assign permission to Manager
        $manager = Role::where('name', 'manager')->first();
        $manager->givePermissionTo([
            'menu-staff',
            'menu-teacher',
            'menu-student',
            'menu-class',
            'menu-attendance',
            'menu-documents',
            'menu-fees',
            'menu-timetable',
            'menu-transport',
            'menu-finance',
            'menu-class-work',
            'menu-home-work',
            'menu-salary',
            'menu-library',
            'menu-software-plan',
            'menu-payment-plan',
            'read fees-consession',
            'create all-profile',
            'read self-attendance',
            'read teacher',
            'read student',
            'read class',
            'create section',
            'read staff-attendance',
            'read staff-attendance-register',
            'read student-attendance',
            'read student-attendance-register',
            'read fees',
            'create fees',
            'read timetable',
            'read transport',
            'create transport',
            'read transport-fees',
            'create transport-fees',
            'create transport-assign-driver',
            'read transport-student',
            'read finance-incoming',
            'read finance-expences',
            'read class-work',
            'create class-work',
            'read home-work',
            'create home-work',
            'read salary',
            'read salary-distribute',
            'read document-collage-logo',
            'read document-sign',
            'read document-id-card',
            'read document-fees-card',
            'read document-scheam',
            'read document-admit-card',
            'read document-number-sheet',
            'read document-mark-sheet',
            'read exam-exam-type',
            'create staff-admin',
            'read staff-admin',
            'update staff-admin',
            'delete staff-admin',
            'create staff-manager',
            'read staff-manager',
            'update staff-manager',
            'delete staff-manager',
            'create staff-principle',
            'read staff-principle',
            'update staff-principle',
            'delete staff-principle',
            'create staff-incharge',
            'read staff-incharge',
            'update staff-incharge',
            'delete staff-incharge',
            'create staff-class-teacher',
            'read staff-class-teacher',
            'update staff-class-teacher',
            'delete staff-class-teacher',
            'create staff-teacher',
            'read staff-teacher',
            'update staff-teacher',
            'delete staff-teacher',
            'create library',
            'read library',
            'update library',
            'delete library',






        ]);

        // assign permission to Principle
        $principle = Role::where('name', 'principle')->first();
        $principle->givePermissionTo([
            'menu-staff',
            
            'menu-student',
            'menu-class',
            'menu-attendance',
            'menu-fees',
            'menu-timetable',
            'menu-transport',
            'menu-finance',
            'menu-class-work',
            'menu-home-work',
            'menu-salary',
            'menu-documents',
            'menu-exam',
            'menu-library',
            'menu-software-plan',
            'menu-payment-plan',

            'create all-profile',
            'read self-attendance',
            'read attendance-schedules',
            'read staff-incharge',
            'read staff-class-teacher',
            'read staff-teacher',
            'read student',
            'update student',
            'read staff-driver',
            'read class',
            'read staff-attendance',
            'read staff-attendance-register',
            'read student-attendance',
            'read student-attendance-register',
            'read fees',
            'read fees-consession',
            'read fees-collection',
            'read fees-status',
            'read timetable',
            'read transport',
            'read transport-fees',
            'read transport-assign-driver',
            'read transport-student',
            'read finance-incoming',
            'read finance-expences',
            'read class-work',
            'read home-work',
            'read salary',
            'read salary-distribute',
            'read document-collage-logo',
            'read document-sign',
            'read document-id-card',
            'read document-fees-card',
            'read document-scheam',
            'read document-admit-card',
            'read document-number-sheet',
            'read document-mark-sheet',
            'read exam-exam-type',
            'read library',
            

        ]);

        // assign permission to classteacher
        $classteacher = Role::where('name', 'classteacher')->first();
        $classteacher->givePermissionTo([
            'menu-staff',
            'menu-student',
            'menu-fees',
            'menu-timetable',
            'menu-transport',
            'menu-attendance',
            'menu-class-work',
            'menu-home-work',
            'menu-exam',
            'read-self-profile',
            'read student-attendance',
            'read self-attendance',
            'create self-attendance',
            'edit self-attendance',
            'delete self-attendance',
            'read staff-own-principle',

            'create staff-own-principle',
            'update staff-own-principle',
            'delete staff-own-principle',
            'read staff-teacher',
            'read staff-driver',
            'read student' ,
            'read fees',
            'read fees-collection',
            'read fees-status',
            'read timetable',
            'read transport',
            'create transport',
            'read transport-fees',
            'create transport-fees',
            'read transport-root-driver',
            'create transport-root-driver',
            'read transport-student',
            'read class-work',
            'create class-work',
            'read home-work',
            'create home-work',
            'read exam-exam-type',
           


        ]);

        //assign permissions to teacher
        $teacher = Role::where('name', 'teacher')->first();
        $teacher->givePermissionTo([
            'menu-staff',
            'menu-student',
            'menu-fees',
            'menu-timetable',
            'menu-transport',
            'menu-class-work',
            'menu-home-work',
            'menu-exam',
            
            'read-self-profile',
            'read self-attendance',
            'read staff-own-principle',
            'read staff-own-class-teacher',
            'read staff-own-teacher',
            'read student' ,
            'read staff-driver',
            'read fees',
            'create fees',
            'read fees-status',
            'create fees-status',
           
            'read timetable',
            'read transport',
            'create transport',
            'read transport-fees',
            'create transport-fees',
            'read transport-root-driver',
            'create transport-root-driver',
            'read class-work',
            'create class-work',
            'read home-work',
            'create home-work',
            'read exam-exam-type',
           


        ]);

        //assign permissions to student
        $student = Role::where('name', 'student')->first();
        $student->givePermissionTo([
            'menu-staff',
            // 'menu-student',

            //'menu-attendance',
            'menu-fees',
            'menu-timetable',
            'menu-transport',
            'menu-class-work',
            'menu-home-work',
            'menu-exam',
            'menu-leave',

            'read staff-own-principle',
            'read staff-own-class-teacher',
            'read staff-own-teacher',
            'read staff-driver',
            'read-self-profile',

            //'create all-profile',
            'read self-attendance',
            //'read student-attendance',
            //'read student-attendance-register',
            'read fees',
            'create fees',
            'read fees-status',
            'create fees-status',
            
            'read fees-slips',
            'read fees-card',

            'read timetable',
            'read transport',
            'create transport',
            'read transport-fees',
            'create transport-fees',
            'read transport-root-driver',
            'read transport-vehicle-number',

            'read class-work',
            'create class-work',
            'read home-work',
            'create home-work',

            'read leave',
            'create leave',




        ]);
        //assign permissions to parent
        $parent = Role::where('name', 'parent')->first();
        $parent->givePermissionTo([
            'header-academics',
            'menu-syllabus',
            'menu-timetable',
            'menu-notice',
            'menu-exam',
            'read syllabus',
            'read timetable',
            'read notice',
            'check result',
        ]);

        //assign permissions to librarian
        //assign permissions to accountant




    }
}
