<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Spatie\Permission\Models\Role;

class TestController extends Controller
{
  
    function testing(){
        $admin = Role::where('name', 'admin')->first();
        dd($admin) ; 
        $admin->givePermissionTo([
            // 'header-administrate',
            // 'header-academics',
            // 'menu-section',
            // 'menu-class',
            // 'menu-student',
            // 'menu-teacher',
            // 'menu-academic-year',
            // 'menu-subject',
            // 'menu-syllabus',
            // 'menu-timetable',
            // 'menu-semester',
            // 'menu-exam',
            // 'menu-grade-system',
            // 'menu-notice',
            // 'menu-parent',
            // 'menu-account-application',
            // 'manage school settings',
            // 'create section',
            // 'read section',
            // 'update section',
            // 'delete section',
            // 'create class',
            // 'read class',
            // 'update class',
            // 'delete class',
            // 'create class group',
            // 'read class group',
            // 'update class group',
            // 'delete class group',
            // 'create student',
            // 'read student',
            // 'update student',
            // 'delete student',
            // 'create academic year',
            // 'read academic year',
            // 'update academic year',
            // 'delete academic year',
            // 'set academic year',
            // 'create teacher',
            // 'read teacher',
            // 'update teacher',
            // 'delete teacher',
            // 'create subject',
            // 'read subject',
            // 'update subject',
            // 'delete subject',
            // 'promote student',
            // 'read promotion',
            // 'reset promotion',
            // 'graduate student',
            // 'view graduations',
            // 'reset graduation',
            // 'create semester',
            // 'read semester',
            // 'update semester',
            // 'delete semester',
            // 'set semester',
            // 'create syllabus',
            // 'read syllabus',
            // 'update syllabus',
            // 'delete syllabus',
            // 'create timetable',
            // 'read timetable',
            // 'update timetable',
            // 'delete timetable',
            // 'create custom timetable item',
            // 'read custom timetable item',
            // 'update custom timetable item',
            // 'delete custom timetable item',
            // 'create exam',
            // 'read exam',
            // 'update exam',
            // 'delete exam',
            // 'create grade system',
            // 'read grade system',
            // 'update grade system',
            // 'delete grade system',
            // 'create exam slot',
            // 'read exam slot',
            // 'update exam slot',
            // 'delete exam slot',
            // 'create exam record',
            // 'read exam record',
            // 'update exam record',
            // 'delete exam record',
            // 'create notice',
            // 'read notice',
            // 'update notice',
            // 'delete notice',
            // 'check result',
            // 'create parent',
            // 'read parent',
            // 'update parent',
            // 'delete parent',
            // 'read applicant',
            // 'update applicant',
            // 'delete applicant',
            // 'change account application status',
        ]);

    }
}
